spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-wgk04dj5v68sbhre.us.auth0.com/
  
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      
application:
  name: customer-service

server:
  port: 8083

  
auth:
  service:
    url: http://localhost:8094/

auth0:
  audience: https://mockbank/api

